Repository sKawashima/cuigame, pull requests merged in 2019-11, with the labels that each got.

#1 Make servay command
  client/index.ts
  client/package-lock.json
  client/package.json
Labels: size/M

#3 Add map
  client/index.ts
Labels: size/M

#4 Add shoot()
  client/index.ts
Labels: size/S

#5 AddPritter
  client/index.ts
  client/package-lock.json
  client/package.json
Labels: size/M

#7 Divide file to Main and UserActions
  client/index.ts
  client/userActions.ts
Labels: size/L
